### ISSUE TITLE
Improve performance of cached offsets

### ISSUE THREAD

**Issue by loyd** [ing-systems/queue-file#20]
Thanks for the crate and, especially, the caching mechanism. However, it's not ideal, and I have several purposes. 

**Firstly**, offsets should be cached not only on `add()` and `add_n()` calls but also during iteration. For instance, after restarting an application, the cache is empty and following `iter() + remove_n()` sequences are inefficient and can blow IO usage up.

**Secondly**, the offset cache should be based on `VecDeque` instead of `Vec` to avoid `O(n)` on `remove()` calls: https://github.com/ing-systems/queue-file/blob/aa89c0c14c0bb9f8800e858069192f0663ae4784/src/lib.rs#L700

For instance, for 10mil items in the queue, the cache contains 1000 marks for the `Linear` strategy and 3162 marks for the `Quadratic` strategy.

**Thirdly**, modification of all marks here
https://github.com/ing-systems/queue-file/blob/aa89c0c14c0bb9f8800e858069192f0663ae4784/src/lib.rs#L702
can be avoided by storing `n` and adding to each new mark. Sometimes, we need to modify all marks in order to avoid overflow, but only in rare cases.

**Comment by khrs** [comment]
Thank you for your suggestions. I will try integrate it on spare time.

**Comment by khrs** [comment]
@loyd published 1.4.9 with first two suggestions integrated
